version: '2'

services: 
    sugar-v0-mariadb: 
        network_mode: "bridge"
        environment:
            MYSQL_ROOT_PASSWORD: "t0pSECr3t"
        image: mariadb
        container_name: "sugar-v0-mariadb"
        expose:
            - 3306
        ports:
            - "59430:3306"
        restart: always

    sugar-v0:
        network_mode: "bridge"
        build:
            context: ./
        image: "sugar-v0"
        container_name: "sugar-v0"
        links:
            - sugar-v0-mariadb
        expose:
            - 5000
        environment:
            ASPNETCORE_URLS: "http://0.0.0.0:5000"
        restart: always
