version: '2'

services:
  sugar-mariadb: 
    image: mariadb
    network_mode: "bridge"
    environment:
      MYSQL_ROOT_PASSWORD: "t0pSECr3t"
    container_name: sugar-mariadb
    expose:
      - 3306
        
  wait-for-db:
    network_mode: "bridge"
    depends_on:
      - sugar-mariadb
    links:
      - sugar-mariadb
    image: ubuntu:14.04
    container_name: wait-for-db
    command: >
      /bin/bash -c "
        while ! nc -z sugar-mariadb 3306;
        do
          echo sleeping;
          sleep 1;
        done;
        echo Connected!;
      "

  sugar:
    depends_on: 
      - sugar-mariadb
    links:
      - sugar-mariadb
    network_mode: "bridge"
    container_name: sugar
    expose:
      - 5000
    ports:
      - "5000:5000"
    environment:
      ASPNETCORE_URLS: "http://0.0.0.0:5000"
    volumes:
      - /other/docker/sugar/logs:/app/PlayGen.SUGAR.Server.WebAPI/logs    